steps:
- name: 'gcr.io/cloud-builders/dotnet'
  args: [ 'publish', '-c', 'Release' ]
  dir: 'testdir'

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app','deploy','testdir/bin/Release/netcoreapp2.2/publish/app.yaml']
